server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "beans"
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    root: "INFO"
  file:
    name: "C:/SpringbootLektioner/PROJECTS/recommendation-service/logfile.txt"